plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

def releaseVersion = System.getenv('GITHUB_TAG')?.replaceFirst(/^v/, '') ?: mod_version

group = maven_group
version = releaseVersion

base {
    archivesName = mod_id
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.toVersion(java_version)
    targetCompatibility = JavaVersion.toVersion(java_version)
}

loom {
    accessWidenerPath = file("common/src/main/resources/${mod_id}.accesswidener")
}

sourceSets {
    main {
        java {
            srcDir 'common/src/main/java'
            srcDir 'fabric/src/main/java'
        }
        resources {
            srcDir 'common/src/main/resources'
            srcDir 'fabric/src/main/resources'
            exclude 'assets/crittersandcompanions/models/entity/*.bbmodel'
        }
    }
}

repositories {
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }

    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }

    maven {
        url = 'https://raw.githubusercontent.com/Fuzss/modresources/main/maven/'
        content {
            includeGroup 'fuzs.forgeconfigapiport'
            includeGroup 'net.neoforged.fancymodloader'
            includeGroup 'net.neoforged.neoforge'
        }
    }

    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forge_config_port_version}"
    include "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forge_config_port_version}"
    implementation "maven.modrinth:geckolib:${geckolib_version}"
}

tasks.named('processResources', ProcessResources).configure {
    includeEmptyDirs = false

    var replaceProperties = [
            minecraft_version_range    : minecraft_version_range,
            fabric_loader_version_range: fabric_loader_version_range,
            fabric_api_version_range   : fabric_api_version_range,
            java_version               : java_version,
            mod_id                     : mod_id,
            mod_name                   : mod_name,
            mod_author                 : mod_author,
            mod_version                : project.version,
            geckolib_version           : geckolib_version,
            forge_config_port_version  : forge_config_port_version,
    ]

    inputs.properties replaceProperties

    filesMatching(['fabric.mod.json', 'pack.mcmeta']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = java_version.toInteger()
}
