# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
mod_id=crittersandcompanions
mod_name=Critters and Companions
mod_author=Joosh, EterDelta
mod_version=2.3.0
release_type=release

# Common
mc_version=1.21.1
java_version=21

# Neoforge
neoforge_version=21.1.152

# Fabric
fabric_api_version=0.115.1+1.21.1
fabric_loader_version=0.16.10

# Dependencies
geckolib_version=4.7.5.1
porting_lib_version=3.1.0-beta.39
curios_version=9.5.1+1.21.1
trinkets_version=3.10.0

jei_version=19.21.0.247
easy_villager_version=O3M0Xv8Q